CUSTOM_MATRIX = lite
SRC += keyboards/macropad/matrix.c

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

WS2812_DRIVER = vendor

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
